services:
  bdiptv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_VISITORS_API: ${NEXT_PUBLIC_VISITORS_API:-}
        NEXT_PUBLIC_PLAYLIST_URL: ${NEXT_PUBLIC_PLAYLIST_URL:-}
        NEXT_PUBLIC_WORLD_PLAYLIST_URL: ${NEXT_PUBLIC_WORLD_PLAYLIST_URL:-}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH:-}
    container_name: bdiptv
    ports:
      - "3000:8080"
